name: matsci465
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - anyio=4.12.1=pyhcf101f3_0
  - aom=3.9.1=h7bae524_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py311h9408147_2
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.4.0=pyhcf101f3_1
  - babel=2.17.0=pyhd8ed1ab_0
  - backports.zstd=1.3.0=py311hee243d0_0
  - beautifulsoup4=4.14.3=pyha770c72_0
  - bleach=6.3.0=pyhcf101f3_0
  - bleach-with-css=6.3.0=h5f6438b_0
  - blosc=1.21.6=h7dd00d9_1
  - brotli=1.2.0=h7d5ae5b_1
  - brotli-bin=1.2.0=hc919400_1
  - brotli-python=1.2.0=py311hdc60ec4_1
  - brunsli=0.1=he0dfb12_2
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.6=hc919400_0
  - c-blosc2=2.22.0=hb83781b_1
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=2.0.0=py311hd10dc20_1
  - charls=2.4.2=h13dd4ca_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh8f84b5b_1
  - cloudpickle=3.1.2=pyhcf101f3_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - colorspacious=1.1.2=pyhecae5ae_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py311h5a5e7c7_3
  - cpython=3.11.14=py311hd8ed1ab_2
  - cycler=0.12.1=pyhcf101f3_2
  - cytoolz=1.1.0=py311h9408147_1
  - dask-core=2025.12.0=pyhcf101f3_1
  - dav1d=1.2.1=hb547adb_0
  - debugpy=1.8.19=py311hc58e375_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dill=0.4.0=pyhcf101f3_1
  - distributed=2025.12.0=pyhcf101f3_1
  - emdfile=0.0.16=pyhd8ed1ab_1
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - filelock=3.20.3=pyhd8ed1ab_0
  - flexcache=0.3=pyhd8ed1ab_1
  - flexparser=0.4=pyhd8ed1ab_1
  - fonttools=4.61.1=py311ha9b3269_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.1=hce30654_0
  - fsspec=2026.1.0=pyhd8ed1ab_0
  - gdown=5.2.1=pyhd8ed1ab_0
  - giflib=5.2.2=h93a5062_0
  - gmp=6.3.0=h7bae524_2
  - gmpy2=2.2.1=py311hd340a2e_2
  - h11=0.16.0=pyhcf101f3_1
  - h2=4.3.0=pyhcf101f3_0
  - h5py=3.15.1=nompi_py311hd5a25a3_101
  - hdf5=1.14.6=nompi_hd3baa01_104
  - hdf5plugin=6.0.0=py311hb71da84_2
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - hyperspy=2.2.0=pyhd8ed1ab_1
  - hyperspy-base=2.2.0=pyhd8ed1ab_1
  - hyperspy-gui-ipywidgets=2.0.3=pyhd8ed1ab_1
  - hyperspy-gui-traitsui=2.0.1=pyhd8ed1ab_2
  - icu=78.2=h38cb7af_0
  - idna=3.11=pyhd8ed1ab_0
  - imagecodecs=2026.1.14=py311h8b8388e_0
  - imageio=2.37.0=pyhfb79c49_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=7.1.0=pyh5552912_0
  - ipympl=0.9.8=pyhcf101f3_0
  - ipython=9.9.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - json5=0.13.0=pyhd8ed1ab_0
  - jsonpointer=3.0.0=pyhcf101f3_3
  - jsonschema=4.26.0=pyhcf101f3_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.26.0=hcf101f3_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.5.2=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - jxrlib=1.1=h93a5062_3
  - kiwisolver=1.4.9=py311h26d6576_2
  - krb5=1.21.3=h237132a_0
  - lark=1.3.1=pyhd8ed1ab_0
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lcms2=2.18=hdfa7624_0
  - lerc=4.0.0=hd64df32_1
  - libaec=1.1.4=h51d1e36_0
  - libavif16=1.3.0=hb06b76e_2
  - libblas=3.11.0=5_h51639a9_openblas
  - libbrotlicommon=1.2.0=hc919400_1
  - libbrotlidec=1.2.0=hc919400_1
  - libbrotlienc=1.2.0=hc919400_1
  - libcblas=3.11.0=5_hb0561ab_openblas
  - libcurl=8.18.0=he38603e_0
  - libcxx=21.1.8=hf598326_0
  - libdeflate=1.25=hc11a715_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgcc=15.2.0=hcbb3090_16
  - libgfortran=15.2.0=h07b0088_16
  - libgfortran5=15.2.0=hdae7583_16
  - libhwy=1.3.0=h48b13b8_1
  - libjpeg-turbo=3.1.2=hc919400_0
  - libjxl=0.11.1=h3dcb153_7
  - liblapack=3.11.0=5_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libnghttp2=1.67.0=hc438710_0
  - libopenblas=0.3.30=openmp_ha158390_3
  - libpng=1.6.54=h132b30e_0
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.51.2=h1ae2325_0
  - libssh2=1.11.1=h1590b86_0
  - libtiff=4.7.1=h4030677_1
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libzlib=1.3.1=h8359307_2
  - libzopfli=1.0.3=h9f76cd9_0
  - link-traits=1.0.3=pyhd8ed1ab_4
  - llvm-openmp=21.1.8=h4a912ad_0
  - llvmlite=0.46.0=py311h27de090_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4-c=1.10.0=h286801f_1
  - markupsafe=3.0.3=py311ha9b3269_0
  - matplotlib=3.10.8=py311ha1ab1f8_0
  - matplotlib-base=3.10.8=py311h29553df_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mistune=3.2.0=pyhcf101f3_0
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - mpire=2.10.2=pyhd8ed1ab_1
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msgpack-python=1.1.2=py311h5a5e7c7_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - natsort=8.4.0=pyh29332c3_1
  - nbclient=0.10.4=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncempy=1.14=pyhd8ed1ab_0
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.6.1=pyhcf101f3_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numba=0.63.1=py311had9367a_0
  - numexpr=2.14.1=py311h5890ad2_1
  - numpy=2.3.5=py311had1e860_1
  - openjpeg=2.5.4=hbfb3c88_0
  - openjph=0.26.0=h2a4d681_0
  - openssl=3.6.0=h5503f6c_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - partd=1.4.2=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pillow=12.1.0=py311hd37aea2_0
  - pint=0.25.2=pyhcf101f3_0
  - pip=25.3=pyh8b19718_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - pooch=1.8.2=pyhd8ed1ab_3
  - prettytable=3.17.0=pyhd8ed1ab_0
  - prometheus_client=0.24.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.1=py311he363849_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py4dstem=0.14.16=pyhd8ed1ab_0
  - pyaml=25.7.0=pyhe01879c_0
  - pycparser=2.22=pyh29332c3_1
  - pyface=8.0.0=pyhd8ed1ab_2
  - pygments=2.19.2=pyhd8ed1ab_0
  - pylops=2.6.0=pyhd8ed1ab_0
  - pyobjc-core=12.1=py311hce6e4fa_0
  - pyobjc-framework-cocoa=12.1=py311h9049b8e_0
  - pyparsing=3.3.1=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.14=h18782d2_2_cpython
  - python-box=7.3.2=py311h9408147_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.11=8_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32-on-windows=0.1.0=pyh1179c8e_3
  - pyyaml=6.0.3=py311ha9b3269_0
  - pyzmq=27.1.0=py311h13abfa4_0
  - qhull=2020.2=h420ef59_5
  - rav1e=0.7.1=h0716509_3
  - readline=8.3=h46df422_0
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhcf101f3_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rosettasciio-base=0.12.0=py311hc949640_0
  - rpds-py=0.30.0=py311h71babbd_0
  - ruamel.yaml=0.19.1=pyhcf101f3_0
  - ruamel.yaml.clib=0.2.15=py311he363849_1
  - scikit-image=0.26.0=np2py311h1ffa155_0
  - scikit-learn=1.4.2=py311hbfb48bc_1
  - scikit-optimize=0.10.2=pyhd8ed1ab_1
  - scipy=1.17.0=py311he9931d0_0
  - send2trash=2.1.0=pyh5552912_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=hada39a4_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.8.1=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - svt-av1=3.1.2=h12ba402_0
  - sympy=1.14.0=pyh2585a3b_105
  - tblib=3.2.2=pyhcf101f3_0
  - terminado=0.18.1=pyhc90fa1f_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tifffile=2025.12.20=pyhd8ed1ab_0
  - tinycss2=1.5.1=pyhcf101f3_0
  - tk=8.6.13=h892fb3f_3
  - toml=0.10.2=pyhcf101f3_3
  - tomli=2.4.0=pyhcf101f3_0
  - toolz=1.1.0=pyhd8ed1ab_1
  - tornado=6.5.4=py311h9408147_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - traits=7.1.0=py311h9408147_0
  - traitsui=8.0.0=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025c=hc9c84f9_1
  - unicodedata2=17.0.0=py311h9408147_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.6.3=pyhd8ed1ab_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - yaml=0.2.5=h925e9cb_3
  - zeromq=4.3.5=h888dc83_9
  - zfp=1.0.1=ha86207d_5
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhcf101f3_1
  - zlib-ng=2.3.2=hed4e4f5_1
  - zstd=1.5.7=hbf9d68e_6
prefix: /Users/wanghuanzhou/miniforge3/envs/matsci465
